export PATH=$PATH:$HOME/bin

export NIX_PATH=nixpkgs=/nix/var/nix/profiles/per-user/$(whoami)/channels/nixpkgs:$NIX_PATH

emacs --daemon 2>/dev/null

function restart-emacs() {
  emacsclient -e "(kill-emacs)"
  emacs --daemon
}

function rebuild-user() {
  source ~/.bash_profile
  build-user
}

function build-user() {
  nix-env -f '<nixpkgs>' -iA \
    cabal-install \
    emacs \
    ghc \
    lastpass-cli \
    nix-prefetch-git \
    nix-prefetch-zip \
    shellcheck \
    stack \
    tmux
  restart-emacs
}
