export PATH=$PATH:$HOME/bin

emacs --daemon 2>/dev/null

function restart-emacs() {
  emacsclient -e "(kill-emacs)"
  emacs --daemon
}

function rebuild-user() {
  source ~/.bash_profile
  build-user
}

function build-user() {
  nix-env -f '<nixpkgs>' -iA \
    cabal-install \
    emacs \
    ghc \
    nix-prefetch-git \
    nix-prefetch-zip \
    shellcheck \
    stack \
    tmux
  restart-emacs
}
